plugins {
    id "com.android.application"
}

android {
    namespace "com.example.networkmodeswitcher"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.networkmodeswitcher"
        minSdk 31
        targetSdk 35
        versionCode 5
        versionName "1.4"
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.debug
        }
    }

    buildFeatures {
        aidl true
    }
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}
